In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [14]:
movies.head(100)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,165000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",http://www.interstellarmovie.net/,157336,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Interstellar,Interstellar chronicles the adventures of a gr...,724.247784,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2014-11-05,675120017,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,8.1,10867
96,160000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",http://inceptionmovie.warnerbros.com/,27205,"[{""id"": 1014, ""name"": ""loss of lover""}, {""id"":...",en,Inception,"Cobb, a skilled thief who commits corporate es...",167.583710,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-07-14,825532764,148.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Your mind is the scene of the crime.,Inception,8.1,13752
97,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
98,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.thehobbit.com/,49051,"[{""id"": 483, ""name"": ""riddle""}, {""id"": 603, ""n...",en,The Hobbit: An Unexpected Journey,"Bilbo Baggins, a hobbit enjoying his quiet lif...",108.849621,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2012-11-26,1021103568,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,From the smallest beginnings come the greatest...,The Hobbit: An Unexpected Journey,7.0,8297
99,38000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9799,"[{""id"": 542, ""name"": ""street gang""}, {""id"": 83...",en,The Fast and the Furious,Domenic Toretto is a Los Angeles street racer ...,6.909942,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2001-06-22,207283925,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Live life 1/4 mile at a time.,The Fast and the Furious,6.6,3428

In [15]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies = movies.merge(credits, on = 'title')

In [20]:
movies.shape

(4809, 23)

In [21]:
credits.shape

(4803, 4)

In [17]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

# Assuming df contains your dataset and the column names are 'feature1', 'feature2', ..., 'feature7', 'output'
features = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [26]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [27]:
features.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [28]:
features.dropna(inplace=True)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\962423859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features.dropna(inplace=True)

In [35]:
features.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [36]:
features.duplicated().sum()

0

In [37]:
features.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [38]:
#as it is string of lists so we will convert it into list so we can apply the convert function that we made
import ast

In [39]:
#here literal eval from ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [60]:
features['genres'] = features['genres'].apply(convert)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\2440747640.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['genres'] = features['genres'].apply(convert)

In [54]:
features['keywords'] = features['keywords'].apply(convert)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\1801188718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['keywords'] = features['keywords'].apply(convert)

In [55]:
features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [56]:
features['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [57]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break;
    return L

In [58]:
features['cast'] = features['cast'].apply(convert3)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\2220948921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['cast'] = features['cast'].apply(convert3)

In [61]:
features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [62]:
features['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [64]:
def fetchDirector(obj):
    L = []
    
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [68]:
features['crew']= features['crew'].apply(fetchDirector)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3157904441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['crew']= features['crew'].apply(fetchDirector)

In [69]:
features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [71]:
features['overview'] = features['overview'].apply(lambda x:x.split())

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\2517785216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['overview'] = features['overview'].apply(lambda x:x.split())

In [72]:
features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [75]:
features['genres'] = features['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
features['keywords'] = features['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
features['cast'] = features['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
features['crew'] = features['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3001401813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['genres'] = features['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3001401813.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['keywords'] = features['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3001401813.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['cast'] = features['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3001401813.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['crew'] = features['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [76]:
features.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [77]:
features['tags'] = features['overview'] + features['genres'] + features['keywords'] + features['cast'] + features['crew']

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\1000962989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features['tags'] = features['overview'] + features['genres'] + features['keywords'] + features['cast'] + features['crew']

In [80]:
features['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [82]:
new_df = features[['movie_id', 'title', 'tags']]

In [83]:
#converting list to string

In [85]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [86]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [87]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [88]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [89]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [90]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [91]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [126]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words='english')

In [127]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [128]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [129]:
len(cv.get_feature_names_out())

10000

In [130]:
cv.get_feature_names_out()

array(['00', '000', '007', ..., 'zoo', 'zooey', 'zooeydeschanel'],
      dtype=object)

In [131]:
for word in cv.get_feature_names_out():
    print(word)

00
000
007
10
100
10th
11
12
12th
13
14
15
150
15th
16
16th
17
17th
18
1863
1890
18th
18thcenturi
19
1910
1920
1927
1930
1930s
1937
1940
1940s
1941
1944
1945
1950
1950s
1955
1959
1960
1960s
1962
1964
1965
1967
1969
1970
1970s
1971
1972
1973
1974
1976
1977
1979
1980
1980s
1984
1985
1986
1987
1990
1994
1995
1996
1997
1999
19th
19thcenturi
20
200
2000
2001
2002
2003
2004
2007
2008
2009
2011
2012
20th
21st
21stcenturi
22nd
23
24
25
27
28
29
30
300
35
3d
40
400
47
50
500
51
60
60s
70
7th
80
aaron
aaroneckhart
aaronseltz
aarontaylor
abandon
abbi
abbiecornish
abduct
abigailbreslin
abil
abl
aboard
abolitionist
aborigin
abort
abov
abraham
abram
abroad
abrupt
abruptli
absenc
absence
absent
absolut
abstract
absurd
abus
abuse
abusivehusband
academ
academi
academy
accept
acceptance
accepts
access
accid
accident
accidental
acclaim
acclim
accompani
accomplish
account
accountant
accus
accused
ace
achiev
acid
acquaint
acquir
acr
act
action
actionhero
actions
activ
activist
activities
actor
actress
actual
ad
ada
adam
adambeach
adambrodi
adamcarolla
adamdriv
adamgarcia
adamgoldberg
adammckay
adams
adamsandl
adamscott
adamshankman
adapt
add
addict
addiction
addit
addl
adjust
admir
admit
adolesc
adolf
adolfhitl
adopt
adoptivefath
ador
adrian
adrianlyn
adrienbrodi
adrift
adult
adultanim
adulteri
adulthood
adults
advanc
advantag
advantage
adventur
adventure
adventures
adversari
advertis
advic
advice
advis
affair
affect
affection
afflict
affluent
afford
afghanistan
afraid
africa
african
africanamerican
afro
aftercreditssting
afterlif
aftermath
afternoon
ag
age
agediffer
agenc
agency
agenda
agent
agents
aggress
aggressionbyanim
ago
agre
agrees
ahead
aid
aidan
aidanquinn
ail
aim
air
airborn
aircraft
airforc
airplan
airplanecrash
airport
aka
akshaykumar
al
alabama
alan
alanalda
alanarkin
alanrickman
alaska
alaskan
albert
albertbrook
albertfinney
alcatraz
alcohol
alcoholabus
aldou
alec
alecbaldwin
alecguin
alejandroamenábar
alejandrogonzáleziñárritu
alex
alexanderpayn
alexanderskarsgård
alexandradaddario
alexandreaja
alexapenavega
alexia
alexisbledel
alexkendrick
alexpettyf
alexproya
alfi
alfonsocuarón
alfredhitchcock
alfredmolina
algeria
ali
alibi
alic
alice
alicebraga
aliceev
aliciasilverston
aliciavikand
aliciawitt
alien
alienabduct
alienattack
aliencontact
alieninfect
alieninvas
alienlife
alienphenomenon
alienplanet
aliens
alik
alike
alilart
alisonlohman
aliv
alive
alleg
allegedli
allegra
allen
allenhugh
alli
allianc
allies
allow
allur
alon
alongsid
alp
alpacino
alpha
alreadi
alt
alter
altern
alternatedimens
alternatehistori
alternater
alvin
alway
alysonhannigan
alyssa
alzheim
alzheimer
amanda
amandabyn
amandapeet
amandaseyfri
amateur
amaz
amazon
ambassador
amber
amberheard
ambertamblyn
ambit
ambiti
ambul
ambush
amelia
america
americaferrera
american
americanabroad
americancivilwar
americandream
americanfootbal
americanfootballplay
ami
amid
amidst
amnesia
amor
amp
amsterdam
amus
amusementpark
amy
amyadam
amyheckerl
amypoehl
amysmart
ana
anakin
analyst
anarchiccomedi
anarchist
ancient
ancientchina
ancientegypt
ancientgreec
ancientrom
ancientworld
anderson
andi
andiemacdowel
andrew
andrewadamson
andrewdavi
andrewflem
andrewgarfield
andrewniccol
andrewstanton
android
andrzejbartkowiak
andy
andyfickman
andygarcía
andysamberg
andyserki
andytenn
angel
angela
angelabassett
angeles
angelinajoli
angels
anger
angle
angri
angst
ani
anim
animal
animalattack
animalhorror
animals
anjelicahuston
ann
anna
annabel
annabellasciorra
annafari
annafriel
annakendrick
annasophiarobb
anne
annebancroft
annefletch
annehathaway
annehech
annemoss
annetteben
anni
annie
anniversari
announc
annoy
annual
anonym
anoth
answer
answers
ant
antarct
antarctica
antholog
anthoni
anthonyanderson
anthonyhopkin
anthonymacki
anthonyquinn
anthonyrusso
anthropomorph
anti
antic
anticip
antics
antihero
antiqu
antisemit
antiterror
antoinefuqua
anton
antonio
antoniobandera
antonyelchin
anxieti
anyon
anyth
apart
apartheid
apartment
ape
apes
apocalyps
apocalypse
apocalypt
apollo
apostl
appalachia
appar
appear
appears
appl
apple
appli
appoint
appreci
apprehend
apprentic
approach
approaches
april
aquarium
arab
arabian
arbitrarylaw
arch
archaeolog
archaeologist
archenemi
archeolog
archeologist
archer
archeri
architect
archiv
arctic
arduou
area
aren
arena
argument
aris
aristocrat
arizona
arm
armageddon
armandassant
armi
armiehamm
arminmueller
armor
armsdeal
armstrong
army
arnold
arnoldschwarzenegg
arrang
arrangedmarriag
array
arrest
arrested
arriv
arrive
arrives
arrog
arson
art
artgalleri
arthur
articl
artifact
artifici
artificialintellig
artist
artists
arts
artthief
asabutterfield
asgard
ash
ashley
ashleyjudd
ashleytisdal
ashtonkutch
asia
asian
asid
ask
asleep
aspect
asperger
aspir
aspirations
ass
assassin
assassination
assassins
assault
assaultrifl
assembl
assign
assignment
assist
assistant
associ
assort
assum
asteroid
astronaut
asylum
atheist
athlet
atlant
atlanta
atlanticocean
atom
atomegoyan
atomicbomb
atroc
attach
attack
attacks
attempt
attemptedmurd
attempttoescap
attend
attent
attention
attic
attitud
attorney
attract
auction
audienc
audit
audrey
audreytaut
august
aunt
austin
australia
australian
australianoutback
austria
austrian
author
authorities
authority
autism
autist
auto
autobiograph
autobot
automaton
automobilerac
autumn
avail
aveng
averag
avert
aviat
aviv
avoid
await
awak
awaken
awar
award
away
awe
awesom
awkward
awri
awry
ax
axe
axel
babe
babi
baby
babysitt
bachelor
backdrop
background
backpack
backstag
backup
backward
backwat
backwood
backyard
bad
badboss
badli
badluck
badmother
bag
bahama
bahari
bail
bailey
baker
bakeri
bakshi
balanc
balance
balboa
baldwin
ball
ballet
balloon
ballroom
baltasarkormákur
balthazar
baltimor
baltimoremaryland
bammargera
ban
band
bandit
bandits
bangkok
banish
bank
banker
bankrobb
bankrobberi
bankrupt
banner
bannon
bar
barbara
barbarahershey
barbarian
barber
barbershop
barbrastreisand
barcelonaspain
bare
barfight
bargain
barn
barney
baron
barri
barricad
barrier
barrio
barry
barrylevinson
barrypepp
barrysonnenfeld
bars
bart
bas
base
basebal
baseball
basedonarticl
basedoncartoon
basedonchildren
basedoncomicbook
basedonfairytal
basedonfilm
basedongraphicnovel
basedonnovel
basedonplay
basedonshortstori
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basket
basketbal
basketball
bat
bathroom
bathtub
batman
battalion
battl
battle
battleassign
battlefield
battleforpow
baxter
bay
bazluhrmann
bdsm
beach
beachhous
beam
bear
beard
beast
beasts
beat
beaten
beau
beauti
beautiful
beautifulwoman
beauty
becam
becaus
becca
becki
beckon
becom
becominganadult
bed
bedroom
bee
beer
beethoven
befor
befriend
beg
began
beggar
begin
begins
beguil
behavior
behead
belgium
belief
beliefs
believ
bell
bella
belong
belov
beloved
belt
ben
benaffleck
benchaplin
bend
beneath
benedictcumberbatch
benefit
benfost
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennet
bennett
benstil
bent
berlin
berni
berniemac
best
bestfriend
bestfriendsinlov
bet
beth
bethani
betray
betrayal
betroth
bettemidl
better
betti
bettythoma
beverli
beverlyhil
bia
bianca
bibl
biblic
bicker
bicycl
bid
big
bigger
biggest
bigotri
bike
biker
bikini
bilbo
billcondon
billewoodruff
billhad
billi
billion
billionair
billmoseley
billmurray
billnighi
billpaxton
billpullman
billy
billybobthornton
billyconnolli
billycrudup
billycryst
billywild
bind
binocular
bio
biograph
biographi
biolog
biologicalweapon
biologist
biopic
bird
birde
birth
birthday
bisexu
bishop
bit
bite
bitten
bitter
bittersweet
bizarr
black
blackandwhit
blackhol
blackmag
blackmail
blackout
blackpeopl
blacksmith
blade
blake
blakel
blame
blart
blast
blaxploit
blaze
bleek
blend
bless
blind
blinddat
blindnessandimpairedvis
bliss
blizzard
block
blockbust
blofeld
blog
blond
blonde
blood
bloodi
bloodsplatt
bloodthirsti
bloom
blossom
blow
blowjob
blown
blu
blue
blunt
blur
bly
board
boardingschool
boat
boatchas
bob
bobbi
bobby
bobbyfarrelli
bobclark
bobgunton
bobhoskin
bodi
bodies
body
bodyguard
bodyhorror
bohemian
bold
bollywood
bolt
bomb
bomber
bond
bondag
bone
bonniehunt
boo
boobytrap
book
books
boost
boot
boots
booze
border
bore
boredom
boring
born
borrow
boss
boston
botanist
botch
bottl
bought
bounc
bound
boundari
bounti
bountyhunt
bourn
bout
bowl
box
boxer
boxingmatch
boy
boyd
boyfriend
boys
brad
bradanderson
bradbird
braddourif
bradleycoop
bradpitt
bradsilberl
brain
braintumor
brainwash
branch
brand
brandi
brandon
brash
brass
brave
braveri
brawl
brazil
brazilian
breach
break
breakdanc
breakdown
breakfast
breakingthefourthwal
breakup
breast
breath
breckinmey
breed
brendan
brendanfras
brendangleeson
brennan
brent
brentonthwait
brentspin
brettratn
brew
brian
briancox
briandepalma
brianhelgeland
brianlev
brianrobbin
briantaylor
brick
bride
bridesmaid
bridg
bridge
bridgetfonda
brief
briefcas
brielarson
brien
bright
brilliant
bring
brink
britain
british
britisharmi
britishsecretservic
britmarl
brittanymurphi
brittrobertson
broadcast
broadway
brock
broke
broken
broker
bronson
bronx
brood
brook
brooklyn
brooklynnewyorkc
brooks
broom
broth
brothel
brother
brotherbrotherrelationship
brotherhood
brothers
brothersisterrelationship
brought
brown
bruce
bruceberesford
brucecampbel
brucedern
brucegreenwood
brucewilli
bruno
brush
brutal
bryan
bryancranston
bryansing
bryce
brycedallashoward
bu
bubbl
buck
buckley
bud
budapest
buddhism
buddhistmonk
buddi
buddy
buddycomedi
buddycop
budget
buffalo
bug
build
building
built
bull
bullet
bulletwound
bulli
bully
bum
bumbl
bump
bumpi
bunch
bungl
bunker
bunni
buoy
burden
bureaucraci
bureaucrat
burgeon
burglar
burglari
buri
buriedal
burk
burlesqu
burn
burnedal
burnett
burnt
burrsteer
burst
burt
burtlancast
burton
burtreynold
bus
bush
busi
business
businessman
businessstart
businesswoman
busrid
bust
butch
butcher
butler
butt
butterfli
button
buy
buzz
byrn
cabin
cabl
caddi
cadet
cadi
caesar
cage
cain
cairo
cal
calcul
cale
caleb
california
californian
called
callou
calm
calvin
cambodia
camcord
came
camelot
cameo
camera
cameraman
cameron
cameronbright
cameroncrow
camerondiaz
camgigandet
camillabel
camp
campaign
campbel
campbell
campbellscott
campu
campus
canada
canadian
canari
cancer
candi
candid
candl
candlelightvigil
canin
cannabi
cannib
cano
canon
canuxploit
canyon
cao
capabl
capac
cape
caper
capit
capsiz
capsul
capt
captain
captiv
captor
captur
capture
captured
car
caraccid
carbomb
carchas
carcrash
card
cardgam
care
career
carefre
caregiv
caretak
careymulligan
cargo
cargoship
caribbean
carjack
carjourney
carl
carlagugino
carlo
carlossaldanha
carmen
carnag
carniv
carol
carolina
carpenter
carrac
carri
carrie
carriefish
carrier
cars
carsetonfir
cartel
carter
cartoon
cartoonist
caruso
caryelw
casanova
case
casey
caseyaffleck
cash
casino
cast
castl
castle
castrat
casual
cat
cataclysm
catapult
catastroph
catch
cateblanchett
catherin
catherinedeneuv
catherinehardwick
catherinekeen
catherinemccormack
catherineo
catherinezeta
cathol
catholic
catholicpriest
cattl
catwoman
caught
caus
cause
cavalri
cave
cavemen
cebe
cedric
cedrictheentertain
celebr
celebration
celebrity
cell
cellphon
cemeteri
censor
cent
center
centr
central
centuri
centuries
century
ceo
ceremoni
certain
cesar
cgi
chad
chadmichaelmurray
chagrin
chain
chainsaw
chair
chairman
challeng
challenge
chamber
champ
champion
championship
chanc
chance
chang
change
changed
changes
channel
channingtatum
chao
chaos
chaotic
chapel
chapter
charact
character
characters
charg
charismat
chariti
charl
charlesmartinsmith
charless
charli
charlie
charlieday
charliehunnam
charliesheen
charlizetheron
charlott
charlotterampl
charm
chart
chase
chasesandrac
chat
chauffeur
chazzpalminteri
cheat
cheatingwif
check
cheerlead
chef
chelsea
chemic
chemistri
cher
cherish
chest
chevychas
chicago
chicken
chief
child
childabus
childhero
childhood
childhoodfriend
childhoodmemori
childhoodtrauma
childprodigi
children
chile
chili
chill
chimp
china
chinatown
chines
chip
chipmunk
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigni
chocol
choic
choice
choir
chon
choos
chopra
choreograph
chose
chosen
chosenon
chowyun
chri
chriscolumbu
chriscoop
chrisevan
chrishemsworth
chrisklein
chriso
chrispin
chrispratt
chrisrock
chrissand
chrissi
christ
christian
christianbal
christianfilm
christianslat
christin
christina
christinaappleg
christinaricci
christma
christmas
christmascarol
christmasev
christmasparti
christmastre
christoph
christophereccleston
christopherguest
christopherlambert
christopherlloyd
christophermcdonald
christophermcquarri
christophermil
christophermintz
christophernolan
christopherplumm
christopherreev
christopherwalken
christophwaltz
christuck
chriswedg
chrisweitz
chronicl
chu
chuck
chucki
chuckrussel
church
churchchoir
churchservic
cia
ciaagent
ciaránhind
cigarett
cigarettesmok
cigarsmok
cillianmurphi
cincinnati
cinderella
cindi
cinema
circl
circle
circu
circuit
circumst
circumstances
circus
cirqu
citi
cities
citizen
citizens
city
cityruin
civil
civilian
civilization
civilright
civilwar
clad
claim
clair
clairedan
claireforlani
clan
clancybrown
clandestin
clare
clari
clark
clarkgabl
clash
class
classdiffer
classic
classicalmus
classifi
classmat
classmates
classprejudic
classroom
classsocieti
clau
claud
claudevandamm
claudia
claustrophobia
clay
clayton
cleaduval
clean
clear
clerk
clever
client
clients
cliff
clifford
climat
climatechang
climb
climber
clinic
clint
clinteastwood
cliqu
cliveowen
clock
clone
clooney
close
closer
closest
closet
closur
cloth
cloud
clown
club
clubs
clue
clueless
clumsi
clumsyfellow
clutch
coach
coal
coalmin
coast
coastal
coax
cobra
cocain
cocki
cod
code
codi
cody
coffin
cohabit
cohen
cohorts
coke
col
cold
coldwar
cole
colehaus
coleridg
colin
colinfarrel
colinfirth
collaps
collapse
collar
colleagu
colleague
collect
collection
collector
colleg
college
collid
collide
collin
collis
colombia
colon
colonel
coloni
color
colorado
columbia
columbin
columnist
com
coma
comb
combat
combin
come
comeback
comed
comedi
comedian
comedy
comet
comfort
comic
comicbook
comics
coming
comingofag
comingout
command
commander
commando
comment
commerci
commiss
commit
commitment
common
commun
communist
community
compani
companion
company
compass
compel
compet
competit
competition
competitors
compil
complet
complete
complex
complic
complicated
compos
compound
compromis
compton
compuls
comput
computer
computerhack
computerprogram
computerviru
conan
conceal
concentrationcamp
concern
concert
conclusion
concoct
condit
condition
conduct
conductor
confeder
confess
confid
confin
confirm
conflict
confront
confus
congo
congress
congressman
conman
connect
connecticut
connel
conni
connienielsen
connor
conquer
conquest
conrad
conradvernon
conscienc
conscience
consequ
consequences
conserv
consid
conspir
conspiraci
conspiracy
conspiracyofmurd
constant
constantli
construct
consult
consum
contact
contain
contamin
contempl
contemporari
contend
content
contest
contin
continu
contract
contractkil
contractor
control
controversi
convent
converg
convers
convert
convict
convinc
cook
cool
cooper
cop
cope
copi
cops
corbinbernsen
core
coreyfeldman
corki
corleon
corner
corp
corpor
corporation
corps
correct
corrupt
corruptcop
corruption
cortez
cost
costasmandylor
costum
cottag
cotton
couldn
counsel
counselor
count
countdown
counter
counterfeit
countess
countless
countri
countries
country
countryhous
countrylif
countrymus
countrysid
countryside
county
coup
coupd
coupl
couple
couples
courag
courage
cours
course
court
courtcas
courteneycox
courtroom
courtship
cousin
coven
cover
covert
covet
cow
cowardic
cowardli
cowboy
coyot
crab
crack
craft
craig
craiggillespi
craigt
crane
crash
crate
crave
crawford
craze
crazi
creat
creation
creativ
creator
creatur
creature
creatures
credit
creditor
creepi
crew
cri
crime
crimefamili
crimefight
crimes
crimin
criminal
criminals
crisi
crisis
critic
crocodil
cronauer
crook
crop
cross
crossdress
crossfir
crossroad
crow
crowd
crown
crucial
crucifixion
cruel
cruelti
cruis
cruise
crumbl
crusad
crush
cruz
cryogen
cryptic
crystal
cuba
cubagoodingjr
cuban
cube
culinari
cullen
culmin
cult
cultfilm
cultur
culture
cultureclash
cun
cup
cure
curios
curiou
curmudgeonli
current
curs
curse
curtishanson
cusp
custodi
custody
custodybattl
custom
cut
cutthroat
cuttingthecord
cyber
cyberpunk
cyborg
cyclist
cynic
cypher
czech
dad
dagger
daili
dakotafan
dalai
dale
dalton
dam
damag
damien
damon
dan
dana
danaykroyd
danc
dance
dancer
dancingmast
dancingscen
danecook
danedehaan
danfogl
danfutterman
danger
daniel
danielbrühl
danielcraig
danielday
danielespinosa
danielle
danielleharri
danielradcliff
daniels
danielstern
danish
danni
danny
dannyaiello
dannyboyl
dannydevito
dannydy
dannyglov
dannyhuston
dannymcbrid
dannytrejo
dano
danyboon
dar
darci
darcy
dare
dark
darkcomedi
darker
darkest
darkfantasi
darkhero
darkli
darkness
darkpast
darksecret
darnel
darrenaronofski
darrenlynnbousman
darryl
daryl
darylhannah
dash
dastardli
date
dates
daughter
daughters
daunt
dave
davechappel
davi
david
davidarquett
daviday
davidbow
davidcarradin
davidcronenberg
davidcross
daviddobkin
davidduchovni
davidfinch
davidfrankel
davidgordongreen
davidhewlett
davidkoepp
davidlean
davidlynch
davidmorrissey
davidmors
davido
davidoyelowo
davidr
davidschwimm
davidson
davidspad
davidstrathairn
davidthewli
davidtwohi
davidwain
davidzuck
dawn
daxshepard
day
daydream
days
dc
dccomic
dea
deaagent
deacon
dead
deadbodi
deadli
deadliest
deadly
deaf
deal
dealer
dealers
dean
deanparisot
dear
death
deathofafriend
deathoffath
deathpenalti
deathstar
debo
deborah
deborahkaraung
debt
debut
debutant
decad
decade
decades
decapit
deceas
deceit
deceivedwif
decept
deception
decid
decidedli
decim
decis
decision
declar
declin
decor
dedic
deed
deem
deep
deeper
deepest
deepli
deer
defeat
defect
defend
defens
defi
defin
definit
deforestkelley
deform
dejavu
deke
delay
delic
delight
delinqu
deliv
deliveri
delorean
delroylindo
delta
delus
delv
demand
dement
dementia
demimoor
demon
demonicpossess
demons
demonstr
deni
deniserichard
denisleari
denmark
denni
denniegordon
dennisdugan
dennishopp
dennisquaid
dent
dentist
denunci
denzelwashington
depart
department
departmentstor
depend
depict
deport
deposit
depress
depression
depth
deputi
derail
derang
derek
derekluk
dermotmulroney
descend
descent
describ
desert
desertedisland
deserv
design
desir
desk
desol
despair
desper
despit
destin
destination
destini
destiny
destroy
destroyed
destruct
destruction
detect
detective
detent
deterior
determin
detroit
detroitmichigan
deuc
devast
develop
devic
device
devil
devilish
deviou
devis
devito
devlin
devonsawa
devot
devour
dewey
diablo
diabol
diagnos
diagnosis
dialogu
diamant
diamond
dian
diana
diane
dianekeaton
dianekrug
dianelan
diannewiest
diari
dick
dicken
dictat
dictatorship
did
didn
die
died
diego
dies
diet
differ
differences
different
difficult
difficultchildhood
difficulti
dig
digit
digniti
dil
dilemma
dimwit
diner
dinner
dinosaur
diplomat
dire
direct
director
directori
dirt
dirti
dirtycop
disabl
disappear
disappeared
disappears
disappoint
disapprov
disast
disaster
disasterfilm
disastermovi
disastr
disc
disciplin
disco
discov
discoveri
discovery
discuss
diseas
disease
disfigur
disgrac
disgruntl
disguis
disguise
disgust
dish
dishonesti
disillus
disintegr
disney
disord
disorder
dispar
dispatch
display
disput
disrupt
dissect
distanc
distant
distinguish
distract
distress
distribut
district
districtattorney
distrust
disturb
ditch
diva
dive
diver
diverg
divers
divid
divin
divis
divorc
divorce
dj
djimonhouns
dna
doc
dock
doctor
docudrama
document
documentari
documentary
documentaryfilmmak
documents
dodg
doe
does
doesn
dog
dogfight
doggedli
dogs
doing
dole
dolittl
doll
dollar
dolphin
dolphins
dolphlundgren
dom
domdeluis
domest
domesticviol
domhnallgleeson
domin
domination
dominatrix
dominican
dominiccoop
dominicpurcel
dominicsena
dominicwest
don
donald
donaldfaison
donaldpetri
donaldpleas
donaldsutherland
donat
donbluth
doncheadl
doncoscarelli
donkey
donmichaelpaul
donnel
donnieyen
donor
donovan
donut
doom
doomed
doomsday
door
doorman
doorstep
dope
doppelgang
dorado
dorian
dorinda
dormant
dormitori
dorothi
dorsey
doubl
double
doublecross
doublelif
doubt

In [117]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [122]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [125]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\salma\AppData\Local\Temp\ipykernel_7492\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [132]:
from sklearn.metrics.pairwise import cosine_similarity

In [137]:
similarity = cosine_similarity(vectors)

In [138]:
 cosine_similarity(vectors).shape

(4806, 4806)

[(1216, 0.2416214041801052),
 (2409, 0.24043316991025832),
 (3730, 0.22281245492773066),
 (539, 0.22190115272469205),
 (507, 0.21226474130316747)]

In [164]:
import difflib

In [165]:
def recommend(movie):
    
    # Get closest match from title list
    close_matches = difflib.get_close_matches(movie, new_df['title'].values)
    
    if not close_matches:
        print("Movie not found.")
        return
    
    movie = close_matches[0]  # Best match
    
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    
    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:9]
    
    print("Showing results for:", movie)
    print("------------------------")
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [168]:
recommend('Batman')

Showing results for: Batman
------------------------
Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.
The Dark Knight
The Dark Knight Rises
Code of Honor

In [169]:
import pickle

In [170]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [171]:
pickle.dump(new_df.to_dict(), open('movie.pkl', 'wb'))

In [172]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))